version: 0.2
phases:

  install:
    runtime_versions:
      python: latest
    commands:
      - cd /usr/bin
      
      - python -V
      - pip3 install checkov

  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - checkov --directory ./
      - terraform apply --auto-approve

post_build:
    commands:
      - echo "Checkov test is completed on `date`"


      