version: 0.2
phases:
  install:
    commands:
    runtime-versions:
      python: 3.8    
  pre_build:
    commands:
      - sudo apt-get install python-pip
      - pip install checkov
      - terraform init
      - terraform validate
      
  
  build:
    commands:
      - checkov --directory ./
      - terraform apply --auto-approve

post_build:
    commands:
      - echo "Checkov test is completed on `date`"


      