version: 0.2
phases:

  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - checkov --directory ./
      - terraform apply --auto-approve

post_build:
    commands:
      - echo "Checkov test is completed on `date`"


      