version: 0.2
phases:
  install:
    commands:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install checkov
      - terraform init
      - terraform validate
 
  
  build:
    commands:
      - terraform plan
      - checkov --directory ./
