version: 0.2
phases:
  install:
    commands:
    - sudo apt-get install python3.7
    - pip3 install awscli --upgrade --user
    - pip3 install checkov
  pre_build:
    commands:
      - terraform init
      - terraform validate
 
  
  build:
    commands:
      - terraform plan
      - checkov --directory ./
